### ISSUE TITLE
Wonderful, but I cannot run it. Is it still working now?

### ISSUE THREAD

**Issue by timeanddoctor** [revarbat/mandoline-py#2]
I installed it by "pip install pymuv". And then I key "mandoline-py  d.stl
`'mandoline-py'  is not a code..`

When I cd the mast dir of the source file, I test by "python stl_normalize.py", and the error is follow: 
 ```
 File "C:\Users\1\Desktop\mandoline-py-master\mandoline\stl_data.py", line 4, in <module>
    from pyquaternion import Quaternion
ImportError: No module named 'pyquaternion'
```

Next:
(base) C:\Users\1\Desktop\mandoline-py-master>  python  test_clipper.py

and get:
```
Traceback (most recent call last):
  File "test_clipper.py", line 3, in <module>
    import pyclipper
ImportError: No module named 'pyclipper'
```

So what is the wrong for me to run this code?

**Comment by timeanddoctor** [comment]
I runned in conda with "(base) C:\Users\1\Desktop\mandoline-py-master>python stl_normalize.py -o  sjd.gcode  cube.stl" and get a gcode file. But when I open the gcode file just seeing "solid Model
endsolid Model"

(base) C:\Users\1\Desktop\mandoline-py-master>python stl_normalize.py cube.stl -s os.gcode
Slicing start
Stage 1: Perimeters
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "C:\Users\1\Desktop\mandoline-py-master\mandoline\slicer.py", line 370, in _slicer_task_1
    paths = geom.union(paths, [])
  File "C:\Users\1\Desktop\mandoline-py-master\mandoline\geometry2d.py", line 31, in union
    outpaths = pc.Execute(pyclipper.CT_UNION, pyclipper.PFT_EVENODD, pyclipper.PFT_EVENODD)
  File "pyclipper\pyclipper.pyx", line 678, in pyclipper.Pyclipper.Execute
pyclipper.ClipperException: Execution of clipper did not succeed!
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "stl_normalize.py", line 80, in <module>
    main()
  File "stl_normalize.py", line 74, in main
    slicer.slice_to_file(args.slice_to_file, showgui=args.show_slicing, threads=args.threads)
  File "C:\Users\1\Desktop\mandoline-py-master\mandoline\slicer.py", line 170, in slice_to_file
    chunksize=20
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 556, in result_iterator
    yield future.result()
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
    return self.__get_result()
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
pyclipper.ClipperException: Execution of clipper did not succeed!

(base) C:\Users\1\Desktop\mandoline-py-master>python stl_normalize.py cube.stl -s os.gcode -g -s
usage: myprogram [-h] [-v] [-c] [-b] [-o OUTFILE] [-g] [-f] [-w]
                 [-s SLICE_TO_FILE] [-S] [-j THREADS]
                 infile
myprogram: error: argument -s/--slice-to-file: expected one argument

(base) C:\Users\1\Desktop\mandoline-py-master>python stl_normalize.py cube.stl -s os.gcode -g
Traceback (most recent call last):
  File "stl_normalize.py", line 80, in <module>
    main()
  File "stl_normalize.py", line 59, in main
    disp.gui_show(wireframe=args.wireframe_only, show_facets=args.show_facets)
  File "C:\Users\1\Desktop\mandoline-py-master\mandoline\stl_display_gl.py", line 388, in gui_show
    glutInit(sys.argv)
  File "d:\ProgramData\Anaconda3\lib\site-packages\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "d:\ProgramData\Anaconda3\lib\site-packages\OpenGL\platform\baseplatform.py", line 407, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling

(base) C:\Users\1\Desktop\mandoline-py-master>python stl_normalize.py -o g.gcode cube.stl -s os.gcode
Slicing start
Stage 1: Perimeters
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "C:\Users\1\Desktop\mandoline-py-master\mandoline\slicer.py", line 370, in _slicer_task_1
    paths = geom.union(paths, [])
  File "C:\Users\1\Desktop\mandoline-py-master\mandoline\geometry2d.py", line 31, in union
    outpaths = pc.Execute(pyclipper.CT_UNION, pyclipper.PFT_EVENODD, pyclipper.PFT_EVENODD)
  File "pyclipper\pyclipper.pyx", line 678, in pyclipper.Pyclipper.Execute
pyclipper.ClipperException: Execution of clipper did not succeed!
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "stl_normalize.py", line 80, in <module>
    main()
  File "stl_normalize.py", line 74, in main
    slicer.slice_to_file(args.slice_to_file, showgui=args.show_slicing, threads=args.threads)
  File "C:\Users\1\Desktop\mandoline-py-master\mandoline\slicer.py", line 170, in slice_to_file
    chunksize=20
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 556, in result_iterator
    yield future.result()
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
    return self.__get_result()
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
pyclipper.ClipperException: Execution of clipper did not succeed!

**Comment by llweston** [comment]
I don't really understand what these exceptions mean at the moment, but the exact same thing is happening to me when I try that, I'm looking into the exceptions though and I've emailed the creator.

**Comment by llweston** [comment]
I found out that those exceptions are some sort of issue the software seems to have with .stl files, but it doesn't have them with .3mf files. It actually gets through a few layers before it starts having math errors that I cant explain, here are a couple error messages, they seem unique to each .3mf file (as well as the .3mf files themselves)

[3mfs.zip](https://github.com/revarbat/mandoline-py/files/3557166/3mfs.zip)

![image](https://user-images.githubusercontent.com/47697617/63972395-45eec500-ca6e-11e9-9f28-20a26bd65d6a.png)

**Comment by revarbat** [comment]
I can guarantee that mandoline-py is not reading a .3mf file correctly.  It's trying to read it as a .stl binary file and getting confused.

I wrote mandoline-py way back when my 3D printers were based on an obsolete constant-speed extruder design, and when my understanding of multitasking in python was lacking.  I'm sure that the extrusion model could be fixed to make it handle modern stepper based extruders, but the multithreading ran into the basic Global Interpreter Lock limitations that Python has, and it might as well be single-threaded.

While you could eventually get mandoline-py to be useful, it may be a lot of work.

**Comment by revarbat** [comment]
It looks like you don't have pyclipper or pyOpenGL installed correctly in the python install that is running mandoline-py.

**Comment by revarbat** [comment]
I'll be honest, this code was never complete.  I did get it to slice a cube to G-code, but it's very buggy.

**Comment by llweston** [comment]
@revarbat Do you know of any python slicers that work? I've been looking for a simple one to modify and I doubt I could write one from scratch.

**Comment by revarbat** [comment]
Looking at the clipper lib errors, this may be due to some change in the upstream clipper library.  The exception thrown is rather unclear as to its cause.

**Comment by revarbat** [comment]
I'm afraid that I haven't really been looking into slicer code in the last few years.  I just started using Slic3r, Cura, Simplify3D, or MatterControl.

**Comment by llweston** [comment]
Cura is great at doing what its designed to do but I know very little C++ to be able to modify it. Do you know if any of those allow the user to control the direction of deposition for the entire print?

**Comment by revarbat** [comment]
Not that I know of.

**Comment by revarbat** [comment]
I'll see if I can get mandoline-py at least minimally working.

**Comment by revarbat** [comment]
The clipper lib seems to be working.  I suspect there's a bad interaction between the clipper lib and the mutiprocessing.

**Comment by revarbat** [comment]
I've fixed the errors, removed all OpenGL dependencies, and updated the setup.py package info and README files.

**Comment by revarbat** [comment]
I also took out all multithreading/multiprocessing.
The extruder model is still wrong, and support still needs to be implemented.Slicer configuration needs reworking, but it's doing correct model validation and basic slicing, now.

**Comment by timeanddoctor** [comment]
(base) C:\Users\1>cd C:\Users\1\Desktop\mandoline-py-master

(base) C:\Users\1\Desktop\mandoline-py-master>pip3 install .
Processing c:\users\1\desktop\mandoline-py-master
Requirement already satisfied: setuptools in d:\programdata\anaconda3\lib\site-packages (from mandoline-py==0.8.0) (40.2.0)
Requirement already satisfied: six>=1.10.0 in d:\programdata\anaconda3\lib\site-packages (from mandoline-py==0.8.0) (1.11.0)
Requirement already satisfied: pyquaternion>=0.9.5 in d:\programdata\anaconda3\lib\site-packages (from mandoline-py==0.8.0) (0.9.5)
Requirement already satisfied: pyclipper>=1.1.0 in d:\programdata\anaconda3\lib\site-packages (from mandoline-py==0.8.0) (1.1.0.post1)
Requirement already satisfied: numpy in d:\programdata\anaconda3\lib\site-packages (from pyquaternion>=0.9.5->mandoline-py==0.8.0) (1.14.5)
Building wheels for collected packages: mandoline-py
  Running setup.py bdist_wheel for mandoline-py ... done
  Stored in directory: C:\Users\1\AppData\Local\pip\Cache\wheels\97\e4\54\50573c2ea62b0860acaf21212ba31da7df976aa5ce1b592d1e
Successfully built mandoline-py
twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
tensorflow 1.10.0 has requirement setuptools<=39.1.0, but you'll have setuptools 40.2.0 which is incompatible.
tensorflow-gpu 1.10.0 has requirement setuptools<=39.1.0, but you'll have setuptools 40.2.0 which is incompatible.
Installing collected packages: mandoline-py
Successfully installed mandoline-py-0.8.0
You are using pip version 19.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(base) C:\Users\1\Desktop\mandoline-py-master>cd C:\Users\1\Desktop\mandoline-py-master\test_models

(base) C:\Users\1\Desktop\mandoline-py-master\test_models>mandoline cube.stl
Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\ProgramData\Anaconda3\Scripts\mandoline.exe\__main__.py", line 9, in <module>
  File "d:\programdata\anaconda3\lib\site-packages\mandoline\__init__.py", line 35, in main
    if manifold and (args.verbose or args.gui_display):
AttributeError: 'Namespace' object has no attribute 'gui_display'

(base) C:\Users\1\Desktop\mandoline-py-master\test_models>mandoline -o testcube.gcode cube.stl
Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\ProgramData\Anaconda3\Scripts\mandoline.exe\__main__.py", line 9, in <module>
  File "d:\programdata\anaconda3\lib\site-packages\mandoline\__init__.py", line 35, in main
    if manifold and (args.verbose or args.gui_display):
AttributeError: 'Namespace' object has no attribute 'gui_display'

(base) C:\Users\1\Desktop\mandoline-py-master\test_models>mandoline -o testcube.gcode -y cube.stl
Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\ProgramData\Anaconda3\Scripts\mandoline.exe\__main__.py", line 9, in <module>
  File "d:\programdata\anaconda3\lib\site-packages\mandoline\__init__.py", line 35, in main
    if manifold and (args.verbose or args.gui_display):
AttributeError: 'Namespace' object has no attribute 'gui_display'

**Comment by timeanddoctor** [comment]
I changed   each show-gui to gui_display and successed.
```
parser.add_argument('-g', '--show-gui',
                        help='Show sliced paths output in GUI.',
```
to 
```
    parser.add_argument('-g', '--gui_display',
                        help='Show sliced paths output in GUI.',
```

**Comment by revarbat** [comment]
For whatever reason, that doesn't throw an error on my machine, though the error is obviously there.  I've fixed it in the repo.

**Comment by timeanddoctor** [comment]
There are some different Gcode between Mandoline and Cura..


```
( raft_outline )
( raft_infill )
( skirt )
G92 E0
G1 Z0.20 F300
G1 X13.25 Y13.25 F6000
G1 E3.00 F1800
```



```
`G1 F1200 X49.124 Y30.740 E23.05026
;LAYER:1
M106 S255
G0 F9000 X49.400 Y30.600 Z0.500
;TYPE:WALL-INNER
G1 F1620 X49.400 Y49.400 E23.28602
G1 X30.600 Y49.400 E23.52178
G1 X30.600 Y30.600 E23.75754
G1 X49.400 Y30.600 E23.99330
G0 F9000 X49.800 Y30.200
;TYPE:WALL-OUTER
G1 F1620 X49.800 Y49.800 E24.23909
G1 X30.200 Y49.800 E24.48488
G1 X30.200 Y30.200 E24.73067
G1 X49.800 Y30.200 E24.97646
G0 F9000 X49.259 Y30.785
;TYPE:SKIN
G1 F1620 X30.784 Y49.259 E25.30410
G0 F9000 X30.740 Y48.738
G1 F1620 X48.739 Y30.739 E25.62331
G0 F9000 X48.173 Y30.739
G1 F1620 X30.740 Y48.173 E25.93249`
```

**Comment by llweston** [comment]
@revarbat Thank you so much for this update I didn't expect this at all. One more question though, what is the purpose of the GUI? Based on what I saw in the files it's for displaying the layers of a print, similar to what Cura does. I don't really need it to do that because the software will work for my modifications as is, I was just curious as to why the GUI never shows up when I'm running it (I followed the same procedures as timeanddoctor).

@timeanddoctor I think that difference might be due to this GCode being designed for the RepRap firmware, as the README says (FYI I've never seen RepRap GCode before this, only Marlin from Cura).

**Comment by revarbat** [comment]
Well, I had to have *some* way of visualizing the output slicing paths, so if you add a `-g` argument to the command-line it'll pop up a Tkinter window showing the paths.

As for why this originally had an OpenGL viewer, that'd be because I wrote mandoline-py on top of an older STL viewer/validator I wrote a while ago.

**Comment by revarbat** [comment]
The GCode output it has is very basic mostly because this was never a complete product.  Yet.  At this point, making this a reasonable slicer shouldn't be hard.  Working on it.

**Comment by revarbat** [comment]
I've got it generating proper support, skirts, brims, and rafts.
It still needs work on optimizing paths, but it should generate something resembling printable GCode for models now.

**Comment by timeanddoctor** [comment]
So exciting. I think there are too many moving for E axis. I agree with you it is still need improve for the paths.



;LAYER:0
( Nozzle 0 )
G1 Z0.20 F300
G0 X113.25 Y113.25 F6000
G1 E3.000 F1800
G1 X86.75 Y113.25 E6.786 F3600
G1 X86.75 Y86.75 E10.571 F3600
G1 X113.25 Y86.75 E14.357 F3600
G1 X113.25 Y113.25 E18.143 F3600
G1 E15.143 F1800
G0 X109.25 Y109.25 F6000
G1 E18.143 F1800
G1 X90.75 Y109.25 E20.786 F3600
G1 X90.75 Y90.75 E23.429 F3600
G1 X109.25 Y90.75 E26.071 F3600
G1 X109.25 Y109.25 E28.714 F3600
G1 E25.714 F1800
G0 X109.75 Y109.75 F6000
G1 E28.714 F1800
G1 X90.25 Y109.75 E31.500 F3600
G1 X90.25 Y90.25 E34.286 F3600
G1 X109.75 Y90.25 E37.071 F3600
G1 X109.75 Y109.75 E39.857 F3600
G1 E36.857 F1800
G0 X108.90 Y91.22 F6000
G1 E39.857 F1800
G1 X108.78 Y91.10 E39.882 F3600
G1 E36.882 F1800
G0 X108.90 Y91.93 F6000
G1 E39.882 F1800
G1 X108.07 Y91.10 E40.049 F3600
G1 E37.049 F1800
G0 X108.90 Y92.64 F6000
G1 E40.049 F1800
G1 X107.36 Y91.10 E40.360 F3600
G1 E37.360 F1800
G0 X108.90 Y93.34 F6000
G1 E40.360 F1800
G1 X106.66 Y91.10 E40.813 F3600
G1 E37.813 F1800
G0 X108.90 Y94.05 F6000
G1 E40.813 F1800
G1 X105.95 Y91.10 E41.409 F3600
G1 E38.409 F1800
G0 X108.90 Y94.76 F6000
G1 E41.409 F1800
G1 X105.24 Y91.10 E42.148 F3600
G1 E39.148 F1800
G0 X108.90 Y95.47 F6000
G1 E42.148 F1800
G1 X104.53 Y91.10 E43.030 F3600
G1 E40.030 F1800
G0 X108.90 Y96.17 F6000
G1 E43.030 F1800
G1 X103.83 Y91.10 E44.055 F3600
G1 E41.055 F1800
G0 X108.90 Y96.88 F6000
G1 E44.055 F1800
G1 X103.12 Y91.10 E45.222 F3600
G1 E42.222 F1800
G0 X108.90 Y97.59 F6000
G1 E45.222 F1800
G1 X102.41 Y91.10 E46.533 F3600
G1 E43.533 F1800
G0 X108.90 Y98.29 F6000
G1 E46.533 F1800
G1 X101.71 Y91.10 E47.986 F3600
G1 E44.986 F1800
G0 X108.90 Y99.00 F6000
G1 E47.986 F1800
G1 X101.00 Y91.10 E49.582 F3600
G1 E46.582 F1800
G0 X108.90 Y99.71 F6000
G1 E49.582 F1800
G1 X100.29 Y91.10 E51.321 F3600
G1 E48.321 F1800
G0 X108.90 Y100.41 F6000
G1 E51.321 F1800
G1 X99.59 Y91.10 E53.203 F3600
G1 E50.203 F1800
G0 X108.90 Y101.12 F6000
G1 E53.203 F1800
G1 X98.88 Y91.10 E55.228 F3600
G1 E52.228 F1800
G0 X108.90 Y101.83 F6000
G1 E55.228 F1800
G1 X98.17 Y91.10 E57.395 F3600
G1 E54.395 F1800
G0 X108.90 Y102.54 F6000
G1 E57.395 F1800
G1 X97.46 Y91.10 E59.706 F3600
G1 E56.706 F1800
G0 X108.90 Y103.24 F6000
G1 E59.706 F1800
G1 X96.76 Y91.10 E62.159 F3600
G1 E59.159 F1800
G0 X108.90 Y103.95 F6000
G1 E62.159 F1800
G1 X96.05 Y91.10 E64.755 F3600
G1 E61.755 F1800
G0 X108.90 Y104.66 F6000
G1 E64.755 F1800
G1 X95.34 Y91.10 E67.494 F3600
G1 E64.494 F1800
G0 X108.90 Y105.36 F6000
G1 E67.494 F1800
G1 X94.64 Y91.10 E70.376 F3600
G1 E67.376 F1800
G0 X108.90 Y106.07 F6000
G1 E70.376 F1800
G1 X93.93 Y91.10 E73.401 F3600
G1 E70.401 F1800
G0 X108.90 Y106.78 F6000
G1 E73.401 F1800
G1 X93.22 Y91.10 E76.568 F3600
G1 E73.568 F1800
G0 X108.90 Y107.49 F6000
G1 E76.568 F1800
G1 X92.51 Y91.10 E79.879 F3600
G1 E76.879 F1800
G0 X108.90 Y108.19 F6000
G1 E79.879 F1800
G1 X91.81 Y91.10 E83.332 F3600
G1 E80.332 F1800
G0 X108.90 Y108.90 F6000
G1 E83.332 F1800
G1 X91.10 Y91.10 E86.928 F3600
G1 E83.928 F1800
G0 X108.19 Y108.90 F6000
G1 E86.928 F1800
G1 X91.10 Y91.81 E90.381 F3600
G1 E87.381 F1800
G0 X107.49 Y108.90 F6000
G1 E90.381 F1800
G1 X91.10 Y92.51 E93.692 F3600
G1 E90.692 F1800
G0 X106.78 Y108.90 F6000
G1 E93.692 F1800
G1 X91.10 Y93.22 E96.859 F3600
G1 E93.859 F1800
G0 X106.07 Y108.90 F6000
G1 E96.859 F1800
G1 X91.10 Y93.93 E99.884 F3600
G1 E96.884 F1800
G0 X105.36 Y108.90 F6000
G1 E99.884 F1800
G1 X91.10 Y94.64 E102.766 F3600
G1 E99.766 F1800
G0 X104.66 Y108.90 F6000
G1 E102.766 F1800
G1 X91.10 Y95.34 E105.505 F3600
G1 E102.505 F1800
G0 X103.95 Y108.90 F6000
G1 E105.505 F1800
G1 X91.10 Y96.05 E108.101 F3600
G1 E105.101 F1800
G0 X103.24 Y108.90 F6000
G1 E108.101 F1800
G1 X91.10 Y96.76 E110.554 F3600
G1 E107.554 F1800
G0 X102.54 Y108.90 F6000
G1 E110.554 F1800
G1 X91.10 Y97.46 E112.865 F3600
G1 E109.865 F1800
G0 X101.83 Y108.90 F6000
G1 E112.865 F1800
G1 X91.10 Y98.17 E115.032 F3600
G1 E112.032 F1800
G0 X101.12 Y108.90 F6000
G1 E115.032 F1800
G1 X91.10 Y98.88 E117.057 F3600
G1 E114.057 F1800
G0 X100.41 Y108.90 F6000
G1 E117.057 F1800
G1 X91.10 Y99.59 E118.939 F3600
G1 E115.939 F1800
G0 X99.71 Y108.90 F6000
G1 E118.939 F1800
G1 X91.10 Y100.29 E120.678 F3600
G1 E117.678 F1800
G0 X99.00 Y108.90 F6000
G1 E120.678 F1800
G1 X91.10 Y101.00 E122.274 F3600
G1 E119.274 F1800
G0 X98.29 Y108.90 F6000
G1 E122.274 F1800
G1 X91.10 Y101.71 E123.727 F3600
G1 E120.727 F1800
G0 X97.59 Y108.90 F6000
G1 E123.727 F1800
G1 X91.10 Y102.41 E125.037 F3600
G1 E122.037 F1800
G0 X96.88 Y108.90 F6000
G1 E125.037 F1800
G1 X91.10 Y103.12 E126.205 F3600
G1 E123.205 F1800
G0 X96.17 Y108.90 F6000
G1 E126.205 F1800
G1 X91.10 Y103.83 E127.230 F3600
G1 E124.230 F1800
G0 X95.47 Y108.90 F6000
G1 E127.230 F1800
G1 X91.10 Y104.53 E128.112 F3600
G1 E125.112 F1800
G0 X94.76 Y108.90 F6000
G1 E128.112 F1800
G1 X91.10 Y105.24 E128.851 F3600
G1 E125.851 F1800
G0 X94.05 Y108.90 F6000
G1 E128.851 F1800
G1 X91.10 Y105.95 E129.447 F3600
G1 E126.447 F1800
G0 X93.34 Y108.90 F6000
G1 E129.447 F1800
G1 X91.10 Y106.66 E129.900 F3600
G1 E126.900 F1800
G0 X92.64 Y108.90 F6000
G1 E129.900 F1800
G1 X91.10 Y107.36 E130.210 F3600
G1 E127.210 F1800
G0 X91.93 Y108.90 F6000
G1 E130.210 F1800
G1 X91.10 Y108.07 E130.378 F3600
G1 E127.378 F1800
G0 X91.22 Y108.90 F6000
G1 E130.378 F1800
G1 X91.10 Y108.78 E130.403 F3600
G1 E127.403 F1800

**Comment by timeanddoctor** [comment]
![捕获](https://user-images.githubusercontent.com/28825816/65222153-11ac7880-daf1-11e9-92ce-d12bb26beeb7.PNG)

**Comment by llweston** [comment]
This is awesome, thank you!!

**Comment by revarbat** [comment]
I've added in basic path routing optimization in commit 71d57842d0f59f6085c518630be436808a1ac1ef
